default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: alice_development

test:
  <<: *default
  database: alice_test

production:
  <<: *default
  database: alice_production
  username: alice
  password: <%= ENV['ALICE_DATABASE_PASSWORD'] %>
